baseURL: "https://sucicada.github.io/blog"  # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: SuCicada
paginate: 20
theme: hugo-PaperMod
#theme: test


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
disqusShortname: sucicada

minify:
  disableXML: true
  # minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - name: Tags
          url: /tags/
          weight: 10
        - name: About
          url: /about/
#        - name: Discord
#          url: https://discord.gg/ahpmTvhVmp

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  comments: true
  dateFormat: 2006-01-02 15:04:00
  ShareButtons:
    - twitter
    - telegram

  Toc: true
  showtoc: true
  tocopen: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "SuCicada - https://github.com/SuCicada"
  author: SuCicada
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: false
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  # comments: false
  images: ["papermod-cover.png"]

  profileMode:
    enabled: false
    title: PaperMod
    imageUrl: "#"
    imageTitle: my image
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: >
        SuCicada
    Content: >
        <div style="text-align: center;" >
          <h2> 我们的教条是: </h2>
          <ul><br/>
            <li><h3> ◦ 经历苦痛才可抵达乐园。 </h3></li><br/>
            <li><h3> ◦ 思考是人生成功的源泉。 </h3></li><br/>
            <li><h3> ◦ 清楚的知道你要做什么。 </h3></li><br/>
          </ul>
        </div>

  socialIcons:
    - name: github
      url: "https://github.com/SuCicada/"
#    - name: KoFi
#      url: "https://ko-fi.com/adityatelange"
    - name: Rss
      url: "index.xml"

  editPost:
    URL: "https://github.com/SuCicada/mysite-hugo/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  whatsapp:
    disable: true
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
