name: Deploy Hugo PaperMod Demo to Pages

on:
  push:
    paths-ignore:
      - "images/**"
      - "LICENSE"
      - "README.md"
    branches:
      - master
  workflow_dispatch:
    # manual run
    inputs:
#      hugoVersion:
#        description: "Hugo Version"
#        required: false
#        default: "0.83.0"

# Allow one concurrent deployment
#concurrency:
#  group: "pages"
#  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
#permissions:
permissions: write-all

#permissions:
#  pages: write
#  id-token: write
#  issues: write
#  pull-requests: write
#  contents: write
#  repository-projects: write


jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
#    env:
#      HUGO_VERSION: "0.83.0"
    steps:
#      - name: Check version
#        if: ${{ github.event.inputs.hugoVersion }}
#        run: export HUGO_VERSION="${{ github.event.inputs.hugoVersion }}"

      - name: Checkout
        uses:
          actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Hugo CLI
        run: |
          wget -O su-hugo -v https://github.com/SuCicada/su-hugo/releases/download/su-hugo/su-hugo_linux-64 \
          && chmod +x su-hugo && sudo cp su-hugo /bin/
##        ref: source
#          repository: SuCicada/blog
#          ref: exampleSite
#      - name: Setup Pages
#        id: pages
#        uses: actions/configure-pages@v1

      - name: Get Theme
        run: git submodule update --init --recursive

#      - name: Update theme to Latest commit
#        run: git submodule update --remote --merge

      - name: Build with Hugo
        run: |
          su-hugo \
            --buildDrafts --gc --verbose \
#            --baseURL ${{ steps.pages.outputs.base_url }}

#      - name: Upload artifact
#        uses: actions/upload-pages-artifact@v1
#        with:
#          path: ./public
#      - name: Push file
#        env:
#          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
#        run: |
#          cd ./public && git init && git add .
#          git config --global user.name "SuCicada"
#          git config --global user.email "pengyifu@gmail.com"
#          repo="https://SuCicada:${{ secrets.MY_GITHUB_TOKEN }}@github.com/SuCicada/blog.git"
#          git branch -m master
#          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
#          git remote add origin $repo
#          git remote set-url origin $repo
#          git push --force origin master
#          SSH_DEPLOY_KEY: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'public'
          destination-github-username: 'SuCicada'
          destination-repository-name: 'blog'
          user-email: pengyifu@gmail.com
          target-branch: master
#          git config --unset-all http.https://github.com/.extraheader

#      - name: deployf
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
##          PAT: ${{ secrets.PAT }}
#        run: npx gh-pages -d ./public --repo https://github.com/SuCicada/blog.git
  # Deployment job
#  deploy:
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        uses: actions/deploy-pages@v1
